kumuluzee:
  name: weather-service
  version: 1.0.0
  env:
    name: ${KUMULUZEE_ENV_NAME:dev}
  server:
    http:
      port: ${KUMULUZEE_SERVER_HTTP_PORT:8086}
      address: ${KUMULUZEE_SERVER_HTTP_ADDRESS:0.0.0.0}
  # datasources:
  #   - jndi-name: jdbc/HikuDS
  #     connection-url: ${KUMULUZEE_DATASOURCES_DEFAULT_CONNECTIONURL:jdbc:postgresql://localhost:5432/hikudb}
  #     username: ${KUMULUZEE_DATASOURCES_DEFAULT_USERNAME:hikuuser}
  #     password: ${KUMULUZEE_DATASOURCES_DEFAULT_PASSWORD:hikupassword}
  jwt-auth:
    issuer: ${KUMULUZEE_JWT_AUTH_ISSUER}
    jwks-uri: ${KUMULUZEE_JWT_AUTH_JWKS_URI}