kumuluzee:
  name: weather-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8086
      address: 0.0.0.0
  datasources:
    default:
      connectionUrl: ${KUMULUZEE_DATASOURCES_DEFAULT_CONNECTIONURL:jdbc:postgresql://localhost:5432/hikudb}
      user: ${KUMULUZEE_DATASOURCES_DEFAULT_USERNAME:hikuuser}
      password: ${KUMULUZEE_DATASOURCES_DEFAULT_PASSWORD:hikupassword}
  jwt-auth:
    issuer: ${KUMULUZEE_JWT_AUTH_ISSUER}
    jwks-uri: ${KUMULUZEE_JWT_AUTH_JWKS_URI}