replicaCount: 1

environment: dev

image:
  repository: weather-service
  tag: dev-latest
  pullPolicy: Never

database:
  enabled: true
  host: postgres.database.svc.cluster.local
  port: "5432"
  name: hikudb
  schema: weather_service

azure:
  enabled: false

gitops:
  enabled: false

service:
  clusterIP:
    port: 8086
    address: "0.0.0.0"

  nodePort:
    enabled: true
    port: 8086
    nodePort: 30086

jwtAuth:
  issuer: "http://localhost:8080/auth/realms/hiku-dev"
  jwksUri: "http://keycloak.keycloak.svc.cluster.local:8080/auth/realms/hiku-dev/protocol/openid-connect/certs"

health:
  enabled: true
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi